// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class SuggestedMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SuggestedMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201312231623146_SuggestedMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
