// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class testdataAnnotationsforsport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testdataAnnotationsforsport));
        
        string IMigrationMetadata.Id
        {
            get { return "201312081505134_test dataAnnotations for sport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
